server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: zsh-picture-backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zsh_picture
    username: root
    password: 123456
  # Redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      # 允许更大的文件上传体积（默认是1MB）
      max-file-size: 10MB
  profiles:
    active: local

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 智能协同云图库接口文档
    version: v1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.zsh.zshpicturebackend.controller