package com.zsh.zshpicturebackend.api.ai_outpainting;

import cn.hutool.core.annotation.Alias;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

import java.io.Serializable;

/**
 * 创建扩图任务的请求
 */
@Data
public class CreateOutPaintingTaskRequest implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 模型名称，示例值：image-out-painting
     */
    private String model = "image-out-painting";

    /**
     * 输入图像的基本信息
     */
    private Input input;

    /**
     * 输出图像的处理参数
     */
    private Parameters parameters;

    /**
     * 输入图像的基本信息
     */
    @Data
    public static class Input implements Serializable {

        private static final long serialVersionUID = 1L;

        /**
         * 图像URL地址或图像base64数据
         * <p>URL需为公网可访问的地址，支持HTTP或HTTPS协议</p>
         * <p>图像格式：JPG、JPEG、PNG、HEIF、WEBP</p>
         * <p>图像大小：不超过10MB</p>
         * <p>图像分辨率：不低于512×512且不超过4096×4096</p>
         */
        @Alias("image_url")
        private String imageUrl;
    }

    /**
     * 输出图像的处理参数
     */
    @Data
    public static class Parameters implements Serializable {

        private static final long serialVersionUID = 1L;

        /**
         * 逆时针旋转角度，单位：度
         * <p>默认值：0，取值范围：[0, 359]</p>
         */
        private Integer angle;

        /**
         * 图像宽高比
         * <p>可选值：""、"1:1"、"3:4"、"4:3"、"9:16"、"16:9"</p>
         * <p>默认值：""，表示不设置输出图像的宽高比</p>
         */
        @Alias("output_ratio")
        private String outputRatio;

        /**
         * 水平方向扩展比例（图像居中，左右等比扩展）
         * <p>默认值：1.0，取值范围：[1.0, 3.0]</p>
         * <p>示例：输入1000×1000，x_scale=2.0 → 输出2000×1000</p>
         */
        @Alias("x_scale")
        //! 此处必须添加@JsonProperty("xScale")，否则会导致该字段无法接收到前端传来的值，参考 https://www.jb51.net/program/365847giv.htm
        @JsonProperty("xScale")
        private Float xScale;

        /**
         * 垂直方向扩展比例（图像居中，上下等比扩展）
         * <p>默认值：1.0，取值范围：[1.0, 3.0]</p>
         * <p>示例：输入1000×1000，y_scale=2.0 → 输出1000×2000</p>
         */
        @Alias("y_scale")
        //! 此处必须添加@JsonProperty("yScale")，理由同上
        @JsonProperty("yScale")
        private Float yScale;

        /**
         * 在图像上方添加的像素数
         * <p>默认值：0，限制：top_offset + bottom_offset < 3×输入图像高度</p>
         */
        @Alias("top_offset")
        private Integer topOffset;

        /**
         * 在图像下方添加的像素数
         * <p>默认值：0，限制：top_offset + bottom_offset < 3×输入图像高度</p>
         */
        @Alias("bottom_offset")
        private Integer bottomOffset;

        /**
         * 在图像左侧添加的像素数
         * <p>默认值：0，限制：left_offset + right_offset < 3×输入图像宽度</p>
         */
        @Alias("left_offset")
        private Integer leftOffset;

        /**
         * 在图像右侧添加的像素数
         * <p>默认值：0，限制：left_offset + right_offset < 3×输入图像宽度</p>
         */
        @Alias("right_offset")
        private Integer rightOffset;

        /**
         * 是否开启图像最佳质量模式
         * <p>默认值：false，设为true可获取更多细节，但耗时成倍增加</p>
         */
        @Alias("best_quality")
        private Boolean bestQuality;

        /**
         * 是否限制输出图像文件大小
         * <p>默认值：true，当输入图像单边长度≤10000时，输出图像文件在5MB以下</p>
         * <p>建议设置为true，当前不支持大于10MB的图像处理</p>
         */
        @Alias("limit_image_size")
        private Boolean limitImageSize;

        /**
         * 是否添加"Generated by AI"水印
         * <p>默认值：true，水印位于输出图像左下角</p>
         */
        @Alias("add_watermark")
        private Boolean addWatermark;
    }
}